### ISSUE TITLE
install on mac osx problem name '_C' is not defined

### ISSUE THREAD

**Issue by rodtaq2015** [AlexChristensen/transforEmotion#4]
Hello
i did the install on R on MacOSX
and have this issue name '_C' is not defined
Many thx in advance
R

RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
name '_C' is not defined

Python Exception Message ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Traceback (most recent call last):
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/Users/Mactaqhome/Library/r-miniconda/envs/r-reticulate/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/pipelines/__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/image_transforms.py", line 44, in <module>
    import torch
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 119, in _find_and_load_hook
    return _run_hook(name, _hook)
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 93, in _run_hook
    module = hook()
  File "/Library/Frameworks/R.framework/Versions/4.2/Resources/library/reticulate/python/rpytools/loader.py", line 117, in _hook
    return _find_and_load(name, import_)
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/torch/__init__.py", line 465, in <module>
    for name in dir(_C):
NameError: name '_C' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/Users/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/transformers/utils/import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
name '_C' is not defined

**Comment by AlexChristensen** [comment]
@rodtaq2015,

Thanks for tagging this error -- I've run into it too. It has something to do with the latest {reticulate} package.

Can you try rolling back {reticulate} and trying again? This solution has worked for me:

```
# Remove {reticulate}
remove.packages("reticulate")
```

Restart R/RStudio

```
# Rollback {reticulate}
devtools::install_version(package = "reticulate", version = "1.31")
```

When updating packages after installing this {reticulate} version, you'll have to remember to "uncheck" {reticulate}

In the meantime, I'm looking into a better resolution

**Comment by rodtaq2015** [comment]
Thx for your fast reply, unfortunatly still the same error. I tried also to re-install transforEmotion but unsuccesfull, is it an install problem ? thx

**Comment by atomashevic** [comment]
Hi @rodtaq2015

I'd like to help out with your issue as well.

Prior to installing `transforEmotion` can you run `reticulate::py_discover_config()` and `reticulate::py_module_available('torch')`and paste the results here?

Also, it would be very helpful for solving this issue if you also run `sessionInfo()` after you've encountered the error you have reported and paste the results here.

**Comment by rodtaq2015** [comment]
Hello 
See below
Thanks
R

> Hi @rodtaq2015
> 
> I'd like to help out with your issue as well.
> 
> Prior to installing `transforEmotion` can you run `reticulate::py_discover_config()` and `reticulate::py_module_available('torch')`and paste the results here?
> reticulate::py_discover_config()
python:         /Users/M/Library/r-miniconda/envs/r-reticulate/bin/python
libpython:      /Users/M/Library/r-miniconda/envs/r-reticulate/lib/libpython3.9.dylib
pythonhome:     /Users/M/Library/r-miniconda/envs/r-reticulate:/Users/M/Library/r-miniconda/envs/r-reticulate
version:        3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:52:10)  [Clang 15.0.7 ]
numpy:          /Users/M/Library/r-miniconda/envs/r-reticulate/lib/python3.9/site-packages/numpy
numpy_version:  1.19.5
Message d'avis :
R graphics engine version 15 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed. 
> reticulate::py_module_available('torch')
[1] FALSE

> Also, it would be very helpful for solving this issue if you also run `sessionInfo()` after you've encountered the error you have reported and paste the results here.

R version 4.2.3 (2023-03-15)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS High Sierra 10.13.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] fr_FR.UTF-8/fr_FR.UTF-8/fr_FR.UTF-8/C/fr_FR.UTF-8/fr_FR.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.11       rstudioapi_0.15.0 magrittr_2.0.3    rappdirs_0.3.3    tesseract_5.2.0   here_1.0.1        lattice_0.21-8    xtable_1.8-4      R6_2.5.1          rlang_1.1.1      
[11] fastmap_1.1.1     tools_4.2.3       grid_4.2.3        png_0.1-8         cli_3.6.1         withr_2.5.0       jquerylib_0.1.4   htmltools_0.5.6   ellipsis_0.3.2    rprojroot_2.0.3  
[21] yaml_2.3.7        digest_0.6.33     lifecycle_1.0.3   Matrix_1.5-4.1    shiny_1.7.5       later_1.3.1       sass_0.4.7        promises_1.2.1    memoise_2.0.1     cachem_1.0.8     
[31] mime_0.12         compiler_4.2.3    bslib_0.5.1       reticulate_1.31   jsonlite_1.8.7    httpuv_1.6.11    
>

**Comment by atomashevic** [comment]
Hi @rodtaq2015

Thanks fort the feedback! Miniconda environment looks OK, but some reason it cannot load the `torch` library. 

Does this error occur when you try to install the package or when you try to run `transformer_scores` function?

If you managed to install the package then you can try running this:

```R
reticulate::conda_create("transforEmotion")

reticulate::conda_install("transforEmotion",
  packages = c(
    "torch", "torchvision",
    "torchaudio", "tensorflow",
    "transformers"
  ),
  pip = TRUE
)

reticulate::use_condaenv("transforEmotion", required = TRUE)
reticulate::py_module_available('torch')
```

If this returns `TRUE` then the package should work, you can try to run:

```R
library(transforEmotion)
data(neo_ipip_extraversion)

text <- neo_ipip_extraversion$friendliness[1:5]

# Cross-Encoder DistilRoBERTa
transformer_scores(
 text = text,
 classes = c(
   "friendly", "gregarious", "assertive",
   "active", "excitement", "cheerful"
 )
)
```

**Comment by atomashevic** [comment]
You can also try re-installing the newest version of the package: `devtools::install_github("atomashevic/transforEmotion")`.

New version implements a custom miniconda environment and there are additional checks for major Python dependencies.

**Comment by atomashevic** [comment]
Closed due to the lack of response.

**Comment by rodtaq2015** [comment]
Hello
Sorry Alex I tried but nothing succeed
I let it down
Best

Rodolphe
